### ISSUE TITLE
Permission of the asset will be: allow everyone read on s3. How can I change that?

### ISSUE THREAD

**Issue by rolele** [webpack-contrib/s3-plugin-webpack#82]
Using this config
```
new S3Plugin({
        s3Options: {
          accessKeyId: process.env.AWS_ACCESS_KEY_ID,
          secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY,
          region: 'us-west-2',
        },
        s3UploadOptions: {
          Bucket: 'aa-react-landing-page',
          CacheControl: 'max-age=315360000',
        },
        cloudfrontInvalidateOptions: {
          DistributionId: process.env.CLOUDFRONT_DISTRIBUTION_ID,
          Items: ['/*'],
        },
      })
    ],
```
When my file are uploaded they automaticaly add the permission:

<img width="509" alt="screen shot 2017-08-09 at 12 19 55 pm" src="https://user-images.githubusercontent.com/22406571/29117058-187fd49e-7cfd-11e7-9fad-5fa57991b751.png">

I have a cloudfront in front of this s3 bucket and I want to restrict access to the resource (using the s3 buket url). 
I need to remove this permission for everything to work properly.
Because of this permission the resource will be accessible for the public via the s3 url.

**Comment by thescientist13** [comment]
I think you would want to use [`s3UploadOptions`](https://github.com/webpack-contrib/s3-plugin-webpack#options).  Here is the API for [`putObject`](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#putObject-property), which includes options for ACL.  Scroll down a bit and look for the example _Calling the putObject operation_

**Comment by MikaAK** [comment]
https://github.com/webpack-contrib/s3-plugin-webpack/issues/71
