### ISSUE TITLE
image paths in <img> HTML tags not getting correctly CDN-ized

### ISSUE THREAD

**Issue by thescientist13** [webpack-contrib/s3-plugin-webpack#83]
**Please complete these steps and check these boxes (by putting an `x` inside
the brackets) _before_ filing your issue:**

- [x] I have read and understood this plugin's README
- [x] If filing a bug report, I have included my version of node and s3-plugin-webpack
- [x] If filing a bug report, I have included which OS (including specific OS
  version) I am using.
- [x] If filing a bug report, I have included a minimal test case that reproduces
  my issue.
- [x] **I understand this is an open-source project staffed by someone with a job and
  that any help I receive is done on free time. I know I am not entitled to anything and will be polite and courteous.**
- [x] **I understand my issue may be closed if it becomes obvious I didn't
  actually perform all of these steps or the issue is not with the library itself**

Thank you for adhering to this process! This ensures that I can pay attention to issues that are relevant and answer questions faster.

# Issue Details

If filing a bug report, please include **a list of steps** that describe how to
reproduce the bug you are experiencing. Include your config being passed to the `S3Plugin`.

### Environment
- OS: OSX 10.12.6 (macOS Sierra)
- Node: 6.9.1
- S3 Webpack Plugin: 1.0.0-rc.0

### Description
Please see a repo I made to demonstrate the problem in full
https://github.com/thescientist13/s3-plugin-webpack-testbed

In short, an image path in an `<img>` HTML tag is not getting CDN-ized.  

Example
```html
<div id="home">

  <h1>Yay webpack!</h1>

  <img alt="webpack image should be here" src="./webpack.png">

</div>
```

When bundled, will not have the value of `defaultCDNBase` applied to it in our final bundle
```javascript
function(e,n,t){e.exports='<div id=home> <h1>Yay webpack!</h1> <img alt="webpack image should be here" src='+t(4)+"> </div>"},function(e,n,t){e.exports=t.p+"f78661bef717cf2cc2c2e5158f196384.png"}],[0]);
```

Including it as a `background-image` _will_ work though.
```css
#home {
  width: 40%;
  margin: 0 auto;
  text-align: center;
  background-image: url('./webpack.png');
}
```

```css
#home{width:40%;margin:0 auto;text-align:center;background-image:url(http://123fakepath.cloudfront.net/f78661bef717cf2cc2c2e5158f196384.png)}
```

Of note, I am using **ExtractTextWebpackPlugin** so not sure if that matters, or if it's because in the `background-image` example, `url` is being used?  That said, I figured since even in the non-working example, the filename is getting hashed, it doesn't seem to be an issue with webpack pulling the image into the AST / compilation per se.

Thanks and let me know if you have any questions / need more info!

**Comment by MikaAK** [comment]
Much easier to use file-loader for images and require them in your templates

**Comment by thescientist13** [comment]
Thanks for review @MikaAK .

In regards to this
> Much easier to use file-loader for images and require them in your templates

Can you elaborate / clarify?  In this case, I am currently using [*file-loader*](https://github.com/thescientist13/s3-plugin-webpack-testbed/blob/master/webpack.config.common.js#L45) to process the image in question (a .png) and the image is being referenced from an [HTML template](https://github.com/thescientist13/s3-plugin-webpack-testbed/blob/master/src/home/home.html#L5).

A bit confused on my end what you're suggesting I change.  If I can provide anymore info, please let me know!

**Comment by MikaAK** [comment]
You can use file-loader and [`publicPath`](https://github.com/webpack-contrib/file-loader#publicpath), which if set to `http://example.com/images` will get prefixed onto your images

**Comment by thescientist13** [comment]
ah, gotcha.  I will test this out ASAP and report back if that addresses the issue.   

Thanks for the quick replies!

**Comment by thescientist13** [comment]
Hi @MikaAK , give your suggestion a try, but it didn't seem to work for.  [Here](https://github.com/thescientist13/s3-plugin-webpack-testbed/commit/58f89896e70b131cb77f4511bec4bf6d9ce5e79e) is what I implemented, maybe I misunderstood you?
```
const prodConfig = require('./webpack.config.prod');
const S3Plugin = require('webpack-s3-plugin');
const webpackMerge = require('webpack-merge');
const cdnBase = 'http://123fakepath.cloudfront.net';

module.exports = webpackMerge(prodConfig, {
  // "workaround" for https://github.com/MikaAK/s3-plugin-webpack/issues/73
  output: {
    publicPath: ''
  },

  module: {
    rules: [{
      test: /\.(jpg|png|gif)$/,
      use: [{
        loader: 'file-loader',
        options: {
          publicPath: cdnBase
        }
      }]
    }]
  },

  plugins: [
    new S3Plugin({
      s3Options: {
        accessKeyId: process.env.AWS_ACCESS_KEY_ID,
        secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY,
        region: process.env.AWS_REGION
      },
      s3UploadOptions: {
        Bucket: process.env.AWS_BUCKET
      },
      cdnizerOptions: {
        defaultCDNBase: cdnBase
      }
    })
  ]
});
```

and in the bundle is still missing the prefix
`<img alt="webpack image should be here" src='+t(4)+"> </div>"},function(e,n,t){e.exports=t.p+"fd4c7e1e28b8e587f30ad855f643bfea.png"}],[0])`

**Comment by MikaAK** [comment]
@thescientist13  i don't know if you need to set `output.publicPath` to `''`. See https://survivejs.com/webpack/loading/fonts/#manipulating-file-loader-output-path-and-publicpath

**Comment by thescientist13** [comment]
@MikaAK 
That was needed to work around an issue we discussed in #73

**Comment by MikaAK** [comment]
don't set output.publicPath. Use defaultCDNBase and publicPath for the loader. Setting `ouput.publicPath: ''` isn't a workaround to that problem, omitting it was. In any case I see no reference to the publicPath in the code so I don't think it has any relevance.

**Comment by thescientist13** [comment]
>  Setting ouput.publicPath: '' isn't a workaround to that problem, omitting it was

Hi @MikaAK , so I guess the issue here then seems to lie in that fact that this in using webpackMerge to pull a config that has `output.publicPath` configured to a value.

So should the real solution to be something like:
```
const prodConfig = require('./webpack.config.prod');
const S3Plugin = require('webpack-s3-plugin');
const webpackMerge = require('webpack-merge');
const cdnBase = 'http://123fakepath.cloudfront.net';

delete prodConfig.output.publicPath;

module.exports = webpackMerge(prodConfig, {
   module: {
    rules: [{
      test: /\.(jpg|png|gif)$/,
      use: [{
        loader: 'file-loader',
        options: {
          publicPath: cdnBase
        }
      }]
    }]
  },

  plugins: [
    new S3Plugin({
      s3Options: {
        accessKeyId: process.env.AWS_ACCESS_KEY_ID,
        secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY,
        region: process.env.AWS_REGION
      },
      s3UploadOptions: {
        Bucket: process.env.AWS_BUCKET
      },
      cdnizerOptions: {
        defaultCDNBase: cdnBase
      }
    })
  ]
}
```

**Comment by MikaAK** [comment]
Yep that looks about right, did it work for you @thescientist13 ? cdnizer is really only for adding the public path to the urls of the assets though maybe we can remove it and add a `publicPath` options

**Comment by MikaAK** [comment]
I'm going to close this as this functionality is covered by file/url-loader. Please reopen with them if you are having further issues
