### ISSUE TITLE
Update plz this package

### ISSUE THREAD

**Issue by Xurma2** [webpack-contrib/s3-plugin-webpack#97]
warning webpack-s3-plugin > s3 > graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js

warning webpack-s3-plugin > cdnizer > nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.

**Comment by evilebottnawi** [comment]
PR welcome

**Comment by MikaAK** [comment]
PR is welcome, https://github.com/webpack-contrib/s3-plugin-webpack/pull/96 is started but I don't know appveyor enough to bypass it...
